- name: Check for updates
  hosts: all
  tasks:
    - name: Check for available updates
      shell: cat /var/lib/update-notifier/updates-available | grep 'updates can be'
      register: var_updates
    - debug:
        var: var_updates.stdout_lines

    - name: Check if restart is needed
      stat:
        path: '/var/run/reboot-required'
      register: file_reboot
    - debug:
        msg: "Restart required"
      when:  file_reboot.stat.exists
