- name: Copy files from Samba share to remote host
  hosts: all
  vars:
    samba_share: "//192.168.7.239/share"
    destination_folder: "/root"
  tasks:
  - name: Install SMB client
    package:
      name: smbclient
      state: present
  - name: Copy files from Samba share
    command: "smbclient {{ samba_share }} -U root -c 'prompt;recurse;mget *' -d 0 -A /etc/samba/smb.conf"
    args:
      chdir: "{{ destination_folder }}"
    
  - name: Grant execute on BDF installer
    command: chmod +x /root/lnx-bdf-installer
  - name: run BDF installer
    command: sh lnx-bdf/installer
  - name: CLEAN UP AFTER INSTALLER BELOW
    command: rm lnx-bdf/bdconfigure
  - name: delete file 2
    command: rm lnx-bdf/installer
  - name: delete file 3
    command: rm lnx-bdf/installer.xml
  - name: delete folder
    command: rm -rf lnx-bdf/linux-amd64
